version: "3.4"


services:
  node:
    image: node
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      HOSTNAME: mongo
      DB_NAME: st_docker_db
    env_file: ./.env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  mongo:
    image: mongo
    env_file: ./.env
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
